version: "3.1"

services:
  database:
    image: "postgres:10-alpine"
    restart: "unless-stopped"
    environment:
      POSTGRES_DB: "innovation_factory"
      POSTGRES_USER: "innovation_factory"
      POSTGRES_PASSWORD: "azerty"
    volumes:
      - "innovation_factory:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

volumes:
  innovation_factory:
