version: "3.1"

services:
  app:
    build: "./"
    restart: "unless-stopped"
    links:
      - database
    volumes:
      - "./:/go/src/app"
    ports:
      - 8080:8080
  database:
    image: "postgres:10-alpine"
    restart: "unless-stopped"
    environment:
      POSTGRES_DB: "db_name"
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "db_password"
    volumes:
      - "db_name:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

volumes:
  db_name:
